### ISSUE TITLE
Create 'PERMISSIONS' table query is missing for PostgreSQL.

### ISSUE THREAD

**Issue by Methma** [wso2/carbon-analytics-common#669] opened 2019-05-23 07:18 UTC
**Description:**
The following error is coming during the startup of the dashboard profile after pointing the WSO2_PERMISSIONS_DB to PostgreSQL in SP 4.3.0 and APIM Analytics 2.6.0.

> Caused by: org.wso2.carbon.analytics.permissions.exceptions.PermissionException: Unable to create the 'PERMISSIONS' table.
> ..
>Caused by: java.sql.SQLException: Cannot find database queries for PostgreSQL 11.3 (Debian 11.3-1.pgdg90+1).
> ..
> Caused by: org.wso2.carbon.database.query.manager.exception.QueryMappingNotAvailableException: Mapping value for query: 'table_check' not found in Deployment config Map and Component config Map for database type: 'PostgreSQL' and version '11.3 (Debian 11.3-1.pgdg90+1)'.
	at org.wso2.carbon.database.query.manager.QueryProvider.mergeMapping(QueryProvider.java:105)

It's due to the create table query for [1] is missing for PostgreSQL
[1]. https://github.com/wso2/carbon-analytics-common/blob/322a9088e619d3b7a119f58d105f64d8193d55a4/components/permission-provider/org.wso2.carbon.analytics.permissions/src/main/java/org/wso2/carbon/analytics/permissions/internal/dao/PermissionsDAO.java#L96)]

**Affected Product Version:**
SP-4.3.0
APIM-Analytics-2.6.0

**OS, DB, other environment details and versions:**    
LInux, PostgreSQL 11.3

**Steps to reproduce:**
1. Point WSO2_PERMISSIONS_DB to PostgreSQL in latest WUM updated pack (SP or APIM Analytics)
2. Start the dashboard profile

**Comment by dilini-muthumala** [comment] 2019-05-27 09:49
Closing the issue as this is a duplicate of [1]. 

[1] https://github.com/wso2/product-sp/issues/920

**Closed by dilini-muthumala** 2019-05-27 09:49 UTC
